### ISSUE TITLE
[bug]: Sorting by date is still broken

### ISSUE THREAD

**Issue by neoOpus** [magicoflolis/Userscript-Plus#50]
### Describe the Bug

Hi,

Yesterday after you made it works again, I thought for a second that the sorting by date is working properly again but unfortunatly it is not... If you accept PR I will do the editing myself

### Steps to reproduce the behavior

Click over the sort by date on the header of the list and the sorting isn't working as expected, the years are scrambled...

### Browser

Edge

### Type

Userscript

### URL

x.com

**Comment by magicoflolis** [comment]
Fixed as of v6.7.0

https://github.com/magicoflolis/Userscript-Plus/releases/tag/6.7.0

**Comment by neoOpus** [comment]
Hi,

For some reasons the problem still persists, I tried to reset everything but the dates aren't sorted properly, it seems that it works at but when you scroll you will see that many scripts are from older dates that show among some recent ones... Should I do something specific on my side to get the sorting work as expected?

**Comment by magicoflolis** [comment]
> Hi,
> 
> For some reasons the problem still persists, I tried to reset everything but the dates aren't sorted properly, it seems that it works at but when you scroll you will see that many scripts are from older dates that show among some recent ones... Should I do something specific on my side to get the sorting work as expected? Also do you accept PR?

Yes I accept PR, also if this issue is still happening please send what UserScripts and WebExtensions you have installed.

**Comment by magicoflolis** [comment]
Fixed as of v7.5.0, for real this time
